In [1]:
import pandas as pd
import numpy as np

In [ ]:
#Carregamento e amostragem das primeiras linhas da dataframe


df_alunos = pd.read_csv(r"C:\Users\blood\Documents\bolsistas_2025.csv",low_memory=False)
display(df_alunos.head())

,Numero,Aluno Bolsista,CPF,Curso,Número de registro da atividade na PROEXT,Edital,Valor mensal da bolsa,Período de recebimento da bolsa,Instituto
0,1,Alexandre de Jesus Valverde Júnior,***.895.818-**,Geografia (Licenciatura),276/2024,EDITAL Nº 08/2024/DAEN/DGE/PROENS,"R$700,00",01/08/2024 a 30/04/2026,"Coordenação-Geral de Planejamento, Orçamento e..."
1,2,Ana Caroline Vasconcelos de Almeida,***.800.556-**,ENFERMAGEM (Bacharelado),276/2024,EDITAL Nº 08/2024/DAEN/DGE/PROENS,"R$700,00",01/08/2024 a 30/04/2026,CGPO/SGTES/MS
2,3,Ana Clara Miranda Castro dos Santos,***.697.036-**,Psicologia (Bacharelado),276/2024,EDITAL Nº 08/2024/DAEN/DGE/PROENS,"R$700,00",01/08/2024 a 30/04/2026,CGPO/SGTES/MS
3,4,Ana Lívia da Cruz Wiezel,***.532.858-**,TERAPIA OCUPACIONAL (Bacharelado),276/2024,EDITAL Nº 08/2024/DAEN/DGE/PROENS,"R$700,00",01/08/2024 a 30/04/2026,CGPO/SGTES/MS
4,5,Bárbara Beloti Silva,***.587.328-**,Terapia ocupacional (Bacharelado),276/2024,EDITAL Nº 08/2024/DAEN/DGE/PROENS,"R$700,00",01/08/2024 a 30/04/2026,CGPO/SGTES/MS

In [ ]:
#Descrição estatística da dataframe 


display(df_alunos.describe())

           Numero
count  110.000000
mean    55.500000
std     31.898276
min      1.000000
25%     28.250000
50%     55.500000
75%     82.750000
max    110.000000

In [ ]:
# Tratamento de dados
#Criando uma cópia da dataframe e fazendo as modificações necessárias para facilitar a manipulação dos dados 

df_analise = df_alunos
df_analise = df_analise.drop(columns=['Numero'])
df_analise = df_analise.dropna()
df_analise['Curso'] = df_analise['Curso'].str.strip()
df_analise['Curso'] = df_analise['Curso'].str.title()
df_analise['Valor mensal da bolsa'] = df_analise['Valor mensal da bolsa'].str.strip('R$')
df_analise['Valor mensal da bolsa'] = df_analise['Valor mensal da bolsa'].str.strip('')
df_analise['Valor mensal da bolsa'] = df_analise['Valor mensal da bolsa'].str.replace(',','.')
df_analise['Valor mensal da bolsa'] = df_analise['Valor mensal da bolsa'].astype(float)


display(df_analise)
display(df_analise.info())

,Aluno Bolsista,CPF,Curso,Número de registro da atividade na PROEXT,Edital,Valor mensal da bolsa,Período de recebimento da bolsa,Instituto
0,Alexandre de Jesus Valverde Júnior,***.895.818-**,Geografia (Licenciatura),276/2024,EDITAL Nº 08/2024/DAEN/DGE/PROENS,700.0,01/08/2024 a 30/04/2026,"Coordenação-Geral de Planejamento, Orçamento e..."
1,Ana Caroline Vasconcelos de Almeida,***.800.556-**,Enfermagem (Bacharelado),276/2024,EDITAL Nº 08/2024/DAEN/DGE/PROENS,700.0,01/08/2024 a 30/04/2026,CGPO/SGTES/MS
2,Ana Clara Miranda Castro dos Santos,***.697.036-**,Psicologia (Bacharelado),276/2024,EDITAL Nº 08/2024/DAEN/DGE/PROENS,700.0,01/08/2024 a 30/04/2026,CGPO/SGTES/MS
3,Ana Lívia da Cruz Wiezel,***.532.858-**,Terapia Ocupacional (Bacharelado),276/2024,EDITAL Nº 08/2024/DAEN/DGE/PROENS,700.0,01/08/2024 a 30/04/2026,CGPO/SGTES/MS
4,Bárbara Beloti Silva,***.587.328-**,Terapia Ocupacional (Bacharelado),276/2024,EDITAL Nº 08/2024/DAEN/DGE/PROENS,700.0,01/08/2024 a 30/04/2026,CGPO/SGTES/MS
...,...,...,...,...,...,...,...,...
105,Lucas Gabriel Alves Maia,***.369.176-**,Licenciatura Em Química,155/2021,PS Bolsistas CCCP 33/2025,700.0,2025 - Maio a Dezembro,PROEXT-UFTM
106,Maria Eduarda Gobbi Carvalho,***.434.816-**,Licenciatura Em Ciências Biológicas,156/2021,PS Bolsistas CCCP 33/2025,700.0,2025 - Maio a Dezembro,PROEXT-UFTM
107,Gabriel Fernandes,***.089.348-**,Engenharia Elétrica,54/2021,PS Bolsistas CCult 34/2025,700.0,2025 - Maio a Dezembro,PROEXT-UFTM
108,Júlia Rodrigues de Castro,***.548.331-**,Nutrição,61/2021,PS Bolsistas CCult 34/2025,700.0,2025 - Maio a Dezembro,PROEXT-UFTM
109,Olivia Mello de Souza,***.577.356-**,Psicologia,54/2021,PS Bolsistas CCult 34/2025,700.0,2025 - Maio a Dezembro,PROEXT-UFTM

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 8 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Aluno Bolsista                             110 non-null    object
 1   CPF                                        110 non-null    object
 2   Curso                                      110 non-null    object
 3   Número de registro da atividade na PROEXT  110 non-null    object
 4   Edital                                     110 non-null    object
 5   Valor mensal da bolsa                      110 non-null    float64
 6   Período de recebimento da bolsa            110 non-null    object
 7   Instituto                                  110 non-null    object
dtypes: float64(1), object(7)
memory usage: 7.0+ KB

None